### ISSUE TITLE
Push first version of inventory

### ISSUE THREAD

**Issue by HarisYork** [HarisYork/UnityDevelopments#1]
Push first version for sharing

**Comment by HarisYork** [comment]
First version pushed into master

**Comment by choonhongyeoh0241** [comment]
Noted with thanks. Will look into the codes, seems interesting. Able to implement into 2D development?

**Comment by HarisYork** [comment]
Sure. There are some "collected" and "dropped" functions in inventory script, so question only in interaction with objects. I'll add simple 2D character, item and store into scene and re-worked collider a little
